format="""
$conda\
$directory\
$git_branch\
$git_status\
$character
"""
add_newline = false

[line_break]
disabled = true

[python]
disabled = true

[package]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[nodejs]
disabled = true

[java]
disabled = true

[golang]
disabled = true

[aws]
disabled = true

[conda]
symbol = " "
ignore_base = false
format = '([\[$environment\]]($style)) '

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[git_status]
ahead = '󰁝${count}'
diverged = '󰹹󰁝${ahead_count}󰁅${behind_count}'
behind = '󰁅${count}'

[hostname]
ssh_symbol = " "

[memory_usage]
symbol = "󰍛 "

[os]
format = "@ [$symbol]($style) "
style = "bold blue"
disabled = true

[os.symbols]
Fedora = " "
Linux = " "
Macos = " "
Ubuntu = " "
Windows = "󰍲 "

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = true
show_always = true
